language: android

before_install:
  - yes | sdkmanager "platforms;android-30"

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - extra-android-m2repository
    - extra-android-support
    - android-30

jdk:
  - oraclejdk8

script:
  - chmod +x gradlew
  - ./gradlew clean build --stacktrace --info


notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
